### ISSUE TITLE
update_sd_model  'pipe' is not defined

### ISSUE THREAD

**Issue by realyn** [williamyang1991/FRESCO#13]
when switching models other than SG161222/Realistic_Vision_V2.0

   File "E:\FRESCO\webUI.py", line 149, in update_sd_model
     self.pipe.scheduler = DDPMScheduler.from_config(pipe.scheduler.config)
NameError: name 'pipe' is not defined

**Comment by williamyang1991** [comment]
I have just fixed this bug. Please update the `webUI.py`
from
```
self.pipe.scheduler = DDPMScheduler.from_config(pipe.scheduler.config)
```
to
```
self.pipe.scheduler = DDPMScheduler.from_config(self.pipe.scheduler.config)
```

**Comment by realyn** [comment]
thank u
