### ISSUE TITLE
python video_blend.py Cannot run

### ISSUE THREAD

**Issue by CHMimilanlan** [williamyang1991/FRESCO#33]
I ran the command below
"python video_blend.py ./output/music/ --key keys --key_ind 0 26 36 54 72 87 107 122 132 159 173 183 194 206 217 229 239  --output ./output/music/blend.mp4 --fps 24 --n_proc 4 -ps"
which is get by command "python run_fresco.py ./config/config_music.yaml"
But I get the error output below:

/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
self.stylized_imgs[i - 1]: ./output/music/out_194/0194.jpg
self.stylized_imgs[i - 1]: ./output/music/out_194/0195.jpg
[ WARN:0@5.118] global loadsave.cpp:248 findDecoder imread_('/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/output/music/out_194/0195.jpg'): can't open/read file: check file path/integrity
Process Process-4:
Traceback (most recent call last):
  File "/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 118, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 104, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/src/ebsynth/blender/guide.py", line 100, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
self.stylized_imgs[i - 1]: ./output/music/out_72/0072.jpg
self.stylized_imgs[i - 1]: ./output/music/out_72/0073.jpg
[ WARN:0@6.690] global loadsave.cpp:248 findDecoder imread_('/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/output/music/out_72/0073.jpg'): can't open/read file: check file path/integrity
Process Process-2:
Traceback (most recent call last):
  File "/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 118, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 104, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/src/ebsynth/blender/guide.py", line 100, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
self.stylized_imgs[i - 1]: ./output/music/out_0/0000.jpg
self.stylized_imgs[i - 1]: ./output/music/out_0/0001.jpg
[ WARN:0@8.738] global loadsave.cpp:248 findDecoder imread_('/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/output/music/out_0/0001.jpg'): can't open/read file: check file path/integrity
Process Process-1:
Traceback (most recent call last):
  File "/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 118, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 104, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/src/ebsynth/blender/guide.py", line 100, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
self.stylized_imgs[i - 1]: ./output/music/out_132/0132.jpg
self.stylized_imgs[i - 1]: ./output/music/out_132/0133.jpg
[ WARN:0@9.133] global loadsave.cpp:248 findDecoder imread_('/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/output/music/out_132/0133.jpg'): can't open/read file: check file path/integrity
Process Process-3:
Traceback (most recent call last):
  File "/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/alg_vepfs/public/miniconda_dirs/envs/chm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 118, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 104, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/src/ebsynth/blender/guide.py", line 100, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
ebsynth: 9.930143356323242
run_ebsynth done!
video_sequence.get_key_img(i): ./output/music/keys/0000.png
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0001.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0002.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0003.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0004.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0005.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0006.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0007.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0008.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0009.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0010.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0011.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0012.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0013.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0014.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0015.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0016.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0017.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0018.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0019.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0020.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.067] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0021.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0022.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0023.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0024.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_0/0025.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0026.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0001.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0002.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0003.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0004.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0005.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0006.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0007.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0008.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0009.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0010.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0011.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0012.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0013.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0014.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0015.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0016.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0017.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0018.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0019.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0020.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0021.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0022.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0023.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0024.jpg'): can't open/read file: check file path/integrity
[ WARN:0@12.068] global loadsave.cpp:248 findDecoder imread_('./output/music/out_26/0025.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 319, in <module>
    main(args)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 279, in main
    process_seq(video_sequence, i, blend_histogram, blend_gradient)
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 209, in process_seq
    dist1s.append(load_error(bin_a, img_shape))
  File "/alg_vepfs/private/panfayu/chm/xiaozaza/FRESCO/video_blend.py", line 168, in load_error
    with open(bin_path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: './output/music/out_0/0001.bin'

I am extremely confused.....................
Since I get the output images by official command, i didn't get corresponding images as supposed.

**Comment by williamyang1991** [comment]
Turn on the log by setting OPEN_EBSYNTH_LOG = True
And check whether you give the execute permission of ebsynth

see https://github.com/williamyang1991/FRESCO/issues/26#issuecomment-2016438310

**Comment by CHMimilanlan** [comment]
Thanks for your immediate response, I get the key:

/bin/sh: 1: ./src/ebsynth/deps/ebsynth/bin/ebsynth: Permission denied

This problem really troubled me for entire afternoon.

**Comment by williamyang1991** [comment]
Happy you help you solve this annoying problem.
