### ISSUE TITLE
Standalone video_blend usage instructions unclear

### ISSUE THREAD

**Issue by inferno46n2** [williamyang1991/FRESCO#43]
You link back to rerender a video section, but half of those commands do not even function in the supplied version in FRESCO.

The example syntax on rerender a video does not work.

Trying this syntax that I found in a random comment - but constantly getting this error

(diffusers) C:\Users\infer\OneDrive\Documents\Fresco\FRESCO>python video_blend.py /videos/alien/ --key keys --output /output/alien/blend.mp4 --fps 24 --n_proc 100 -ps
Traceback (most recent call last):
  File "video_blend.py", line 308, in <module>
    main(args)
  File "video_blend.py", line 264, in main
    run_ebsynth(video_sequence)
  File "video_blend.py", line 122, in run_ebsynth
    cnt = video_sequence.n_seq // n_process
ZeroDivisionError: integer division or modulo by zero

Please update script usage in FRESCO readme to reflect proper syntax to use.

**Comment by williamyang1991** [comment]
I have updated readme
