### ISSUE TITLE
bad result of white cat

### ISSUE THREAD

**Issue by balabala932131** [williamyang1991/FRESCO#45]
HI! Thanks your great work!
I'm having some problems in white cat result.
This my config, but get bad result
`# data
file_path: './videos/cat_white_input.mp4'
save_path: './output/cat_white_input/A white cat in pink background/'
mininterv: 1 # for keyframe selection
maxinterv: 1 # for keyframe selection

# diffusion
seed: 0
prompt: 'A white cat in pink background'
sd_path: 'stablediffusionapi/flat-2d-animerge' 
use_controlnet: True
controlnet_type: 'hed'  # 'hed', 'canny'
cond_scale: 0.7
use_freeu: False

# video-to-video translation 
batch_size: 8
num_inference_steps: 20
num_warmup_steps: 5
end_opt_step: 15
run_ebsynth: False
max_process: 4

# supporting model
gmflow_path: './model/gmflow_sintel-0c07dcb3.pth'
sod_path: './model/epoch_resnet.pth'
use_salinecy: True`
![0000](https://github.com/williamyang1991/FRESCO/assets/81740459/c5dd688d-8074-4c97-a0e2-5df98f455a94)
Maybe you can help me.

**Comment by williamyang1991** [comment]
Sorry, I miss your issue.

I use controlnet_type of depth map
and num_warmup_steps = -1
