### ISSUE TITLE
Serious Flickering problem 

### ISSUE THREAD

**Issue by Sonia-kong** [williamyang1991/FRESCO#46]
Hi, Thank you for your excellent work. 
I tested a basketball use case, the configuration file is below. I found that the video flickers obviously, is there any way to improve it?
Thanks so much.

> mininterv: 1 # for keyframe selection
maxinterv: 1 # for keyframe selection
seed: 0
prompt: 'In the basketball hall, teenagers wearing red and green uniforms are playing an intense basketball game, with a scorer standing in the distance'
sd_path: 'stablediffusionapi/flat-2d-animerge' 
use_controlnet: True
controlnet_type: 'hed'  # 'depth', 'canny'
cond_scale: 0.7
use_freeu: False 
batch_size: 4
num_inference_steps: 20
num_warmup_steps: 5
end_opt_step: 15
run_ebsynth: False
max_process: 4
gmflow_path: './model/gmflow_sintel-0c07dcb3.pth'
sod_path: './model/epoch_resnet.pth'
use_salinecy: True

https://github.com/williamyang1991/FRESCO/assets/171914194/637ce66d-2771-4af8-8341-98a2cd3b6a30

**Comment by williamyang1991** [comment]
Maybe you can combine diffusion with ebsynth. 
Avoid using diffusion for every frame, and use it for key frames. Then use ebsynth for non-keyframe.
That is 
Avoid using mininterv == maxinterv


mininterv: 1 # for keyframe selection
maxinterv: 1 # for keyframe selection

**Comment by Sonia-kong** [comment]
> Maybe you can combine diffusion with ebsynth. Avoid using diffusion for every frame, and use it for key frames. Then use ebsynth for non-keyframe. That is Avoid using mininterv == maxinterv
> 
> mininterv: 1 # for keyframe selection maxinterv: 1 # for keyframe selection
Got it, thanks. I will try it later. Much thanks to your reply.
