### ISSUE TITLE
Using loops causes colors to get darker

### ISSUE THREAD

**Issue by Sonia-kong** [williamyang1991/FRESCO#50]
Hi, thanks for your wonderful jobs.
I noticed that there is a color correction switch in rerender. 
I would like to ask why there is no such item in Fresco, because I have encountered a problem now: when using diffsers, the color will deepen after multiple iterations.
Thanks a lot.

**Comment by williamyang1991** [comment]
rerender has two color-realted process.
- color correction is to make the results have different color style with the original input video.
- Color-aware AdaIN is to  make the video color consistent with the first frame.
I assume your `color correction` refer to  Color-aware AdaIN?

Color-aware AdaIN is the contribution claimed in rerender, not the contribution of Fresco,
and we didn't notice obvious darken color on our test videos (maybe our video is not long enough to encouter your problem?), 
So we didn't include it in Fresco.

**Comment by Sonia-kong** [comment]
Thanks for your reply.
My test video is indeed quite long. I am considering how to solve the problem of color shift. 
Thanks for your answer.
