### ISSUE TITLE
pull request requirements.txt

### ISSUE THREAD

**Issue by Inferencer** [williamyang1991/FRESCO#7]
sorry still havent figured out pull requests
in requirements.txt

pip install torchvision=0.16.0
should be
pip install torchvision==0.16.0

im on windows annaconda so maybe its different on other systems

**Comment by williamyang1991** [comment]
thank you. I fixed this typo!

**Comment by philtsip** [comment]
this implements https://github.com/williamyang1991/FRESCO/pull/9 :)
